---
title: Goethe University RevealJS Slides
subtitle: With examples
context: Distributed via GitHub/tisprang
format:
  gu-reveal-revealjs: default
author:
  - name: Timo Sprang
    url: https://www.timo-sprang.net
    orcid: 0009-0005-3798-7747
    email: sprang@soz.uni-frankfurt.de
    affiliation:
      - name: Goethe University
        url: https://www.fb03.uni-frankfurt.de/92868250/Willkommen_am_Institut_f%C3%BCr_Politikwissenschaft
        city: Frankfurt am Main
lang: de
---

```{r}
#| label: setup
#| echo: false

library(gufunctions)
```

## Incremental Content {data-name="Standard Slides"}

::: {.incremental}
- Incremental Bullet 1
- Incremental Bullet 2
:::

::: {.nonincremental}
- Standard Bullet 1
- Standard Bullet 2
::: 

## Columns

::::{.columns}

::: {.column width="20%"}
First columns with 20 % width
:::

::: {.column width="70%"}
Second column with 70 % width
:::

::: {.column width="10%"}
Third column with 10 % width
:::

::::

## Smaller content {.smaller}

- Smaller bullet
- Second smaller bullet

## Scrollable content {.scrollable}

- One
- Two
- Three
- Four
- Five
- Six
- Seven
- Eight
- Nine
- Ten
- Eleven
- Twelve

## Footnotes and aside

- Bullet 1^[with a footnote]
- Bullet 2
- Bullet 3

::: aside
Some aside content
:::

##
Simplemenu has a solution for that. Make your presentation in a flat structure (no nested sections) and turn the `flat` option to `true`. Then, if a data-name is set for a slide, any following slides will keep that menu name.

<p class="small">Of course, you can set it to stop inheriting the name as well.</p>


## Set it up {data-name="Set it up"}



## HTML Markup {data-name="Chapter 555"}
Build your presentation in a flat way (no nested slides). Then give your sections a `data-name`:

``` markdown
## Chapter one {data-name="Chapter 1"}
<!-- The 'Chapter 1' menu-item will be active for this slide -->
Lorem ipsum sit dolor amet

## Another slide 
<!-- The 'Chapter 1' menu-item will be active for this slide -->
Lorem ipsum sit dolor amet

## Chapter two {data-name="Chapter 2"}
<!-- The 'Chapter 2' menu-item will be active for this slide -->
Lorem ipsum sit dolor amet
```

## {data-name="Chapter 5556"}
To avoid Quarto creating nested sections, set `section-divs: false` and use dividers to separate your slides.

``` yaml
format:
  revealjs:
    section-divs: false
```

``` markdown
## Chapter one {data-name="Chapter 1"}
<!-- The 'Chapter 1' menu-item will be active for this slide -->
Lorem ipsum sit dolor amet

---

## Another slide
<!-- The 'Chapter 1' menu-item will be active for this slide -->
Lorem ipsum sit dolor amet

---

## Chapter two {data-name="Chapter 2"}
<!-- The 'Chapter 2' menu-item will be active for this slide -->
Lorem ipsum sit dolor amet
```

---

## {data-name="Chapter 55576"}
Any slides following a slide with a data-name will keep that menu name.

---

## {data-sm="false"}
To stop inheriting the previous slide menu name, start a new named section, or add `data-sm="false"` to your slide.

``` markdown
## Chapter one {data-name="Chapter 1"}
<!-- The 'Chapter 1' menu-item will be active for this slide -->
Lorem ipsum sit dolor amet

## Another slide 
<!-- The 'Chapter 1' menu-item will be active for this slide -->
Lorem ipsum sit dolor amet

## Last slide {data-sm="false"}
Lorem ipsum sit dolor amet
```

## That’s it!

## More demos {data-name="More demos"}

For more demos go to the [Simplemenu plugin](https://github.com/Martinomagnifico/reveal.js-simplemenu) for Reveal.js. 
Not all of the options in the regular plugin are available in the Quarto plugin.